version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: hn-watcher-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin  # You should change this in production
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always   # Ensures container automatically restarts
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:
    driver: local 