name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv & set Python
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - uses: extractions/setup-just@v3
        with:
          just-version: '1.40.0'

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run checks
        run: just check
